### ISSUE TITLE
Please add original quality image size.

### ISSUE THREAD

**Issue by zby1234** [Spark-NF/twitter_media_downloader#11]
url add ":orig" gets full size of image, higher quality than "large"
e.g.
https://pbs.twimg.com/media/D_LjaAtUIAA7kEu.jpg:large 1363x2048
https://pbs.twimg.com/media/D_LjaAtUIAA7kEu.jpg:orig  2637x3962

**Comment by Spark-NF** [comment]
Indeed, it would seem I overlooked the possibility of other sizes, since Twitter's API documentation only lists `thumb`, `small`, `medium`, and `large` sizes:
https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#media-size

I'll push a fix to allow for the `orig` size as well.

**Comment by zby1234** [comment]
url add "?format=jpg&name=orig" also can gets full size of image.

**Comment by zby1234** [comment]
@Spark-NF url add "?format=jpg&name=orig" also can gets full size of image as well.

**Comment by Spark-NF** [comment]
Does it make any difference with `:orig`?
