### ISSUE TITLE
No errors but fails to run

### ISSUE THREAD

**Issue by Purefreeman** [Spark-NF/twitter_media_downloader#13]
![Screenshot (2)](https://user-images.githubusercontent.com/20708611/72668890-5b678a00-3a23-11ea-8708-152118079ef1.png)

i ran the following code `python twitter_media_downloader.py -o out -f "%type%s/[%date%] %filename%.%ext%" -s large -r -u twitter` fails to display anything, also not indicating what's wrong.

**Comment by Spark-NF** [comment]
Hello

Could you tell me what version of Python you are using?
You can find out by doing `python -V`.

I just tried your command with both `3.7.3` (Cmd) and `2.7.14` (Cygwin) and both gave me the same result:
```
Tweets: 51
Retweets: 1
Parsed: 52
Files: 0
Urls:
- periscope: 0
- instagram: 0
- others: 2
Text only: 52
Total: 54
```

**Comment by Purefreeman** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/20708611/72685223-02a9f700-3ae0-11ea-9e62-c7c5db54233a.png)

**Comment by Bionus** [comment]
Either your Python or prompt configuration has some issue if you can't even get your python version with `python -V`.

I suggest:
* Ensuring you don't have some weird install of python with `where python`
* Trying to run Python using PowerShell instead of CMD
* Re-installing Python (https://www.python.org/downloads/windows/), preferably the 3.X branch but 2.x also works with this program

In any case, the lack of output doesn't come from this program, so I'll close this issue.

**Comment by Spark-NF** [comment]
Either your Python or prompt configuration has some issue if you can't even get your python version with `python -V`.

I suggest:
* Ensuring you don't have some weird install of python with `where python`
* Trying to run Python using PowerShell instead of CMD
* Re-installing Python (https://www.python.org/downloads/windows/), preferably the 3.X branch but 2.x also works with this program

In any case, the lack of output doesn't come from this program, so I'll close this issue.

**Comment by Purefreeman** [comment]
Not sure what went wrong. But all i had to do was repair it; it all seems to be working accordingly. Thank you for your time
