### ISSUE TITLE
Rate Limit NOtify error?

### ISSUE THREAD

**Issue by rhyswj** [Spark-NF/twitter_media_downloader#36]
I'm getting the following error when I run the code:

TypeError: API.__init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'

**Comment by Spark-NF** [comment]
Hello, this is very likely because you were using Tweepy 4 instead of 3. Did you install the requirements via `pip install -r requirements.txt`? It should have said something about it.

In any case, this was just fixed in a PR so you shouldn't be having this issue anymore.
I'll also be bumping dependencies soon to prevent similar issues.
