### ISSUE TITLE
hardcoded No retweets

### ISSUE THREAD

**Issue by sethcohn** [Spark-NF/twitter_media_downloader#5]
The 'use retweets' api argument include_rts is hardcoded to false.  Should be an argument to change this.

**Comment by sethcohn** [comment]
Gah, complicatedly this only works for _some_ retweets.  A retweeted extended_entities using tweet (ie multiple images or video) doesn't work correctly (it shows up as empty, despite the retweeted tweet having multiple images).  Gonna take some work.

**Comment by Spark-NF** [comment]
The issue you must have faced is that when you enable retweets, the object returned by the API is not the original retweeted tweet but simply the "RT ..." message and a pointer to the original tweet.

The actual data is included in the `retweeted_status` of the tweet object, which itself contains the proper `extended_entities` information.

I just added a `-r` / `--retweets` argument to enable downloading medias from retweets, thanks for the suggestion :+1:

If you want to use the original date (so the posting date of the original tweet, not the retweet date), you can use `%original_date%` instead of `%date%`.
