### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by Purefreeman** [Spark-NF/twitter_media_downloader#8]
Python 3.6.4
windows 10

ran this code in the cmd: twitter_media_downloader.py -o out -f checking -s large -u twitter (The reason why i didn't use -f '[%date%] %filename% %ext%' was it always result in this error "twitter_media_downloader.py: error: unrecognized arguments: %filename% %ext%' twitter")

```
Tweets: 2809
Retweets: 0
Parsed: 2809
Files: 1
Urls:
- periscope: 0
- instagram: 0
- others: 254
Text only: 1617
Total: 1872
checking: ok
```

**Comment by Spark-NF** [comment]
Hello 😄 

Sorry for the (very very) late reply.
That's expected, since you used "checking" as filename: all files will be named "checking", so only one will be downloaded. That's what the last line of the log says, the "checking" file has been downloaded successfully:

```
checking: ok
```

If you want to download everything properly, you need to have unique filenames, such as "%filename% %ext%", or whichever you want.

Your "error: unrecognized arguments" is caused by using single quotes instead of double quotes around the `-f` parameter. I updated the README to use double quotes, as single quotes indeed don't work properly on Windows.
